on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Checkout readme repo
        uses: actions/checkout@v4
        with:
          repository: rithik-sandron/GitHub-actions-test
          path: ./GitHub-actions-test
          token: ${{ secrets.R_TOKEN }}

      - name: commit files
        env:
          R_TOKEN: ${{ secrets.R_TOKEN }}
        run: |
          python ./GitHub-actions-test/wk_run.py
          git add -A .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "generated"
          rm -rfd ./GitHub-actions-test
          git push
